// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHK1p5Zq9Xpaq56E7bEIi8raXTbkOVL_U',
    appId: '1:147062760195:web:99692fe4e99a087a647f36',
    messagingSenderId: '147062760195',
    projectId: 'playing-e69b2',
    authDomain: 'playing-e69b2.firebaseapp.com',
    storageBucket: 'playing-e69b2.firebasestorage.app',
    measurementId: 'G-9Z3Y82W8G5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdUf42Dya8fJlr2IEGCpeu7PSXzenwSSg',
    appId: '1:147062760195:android:42540dd2bb36b58b647f36',
    messagingSenderId: '147062760195',
    projectId: 'playing-e69b2',
    storageBucket: 'playing-e69b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByBJndzaYHYFPHU-44pXNgzjt8p-at288',
    appId: '1:147062760195:ios:e9939eb6f6987e1b647f36',
    messagingSenderId: '147062760195',
    projectId: 'playing-e69b2',
    storageBucket: 'playing-e69b2.firebasestorage.app',
    iosBundleId: 'com.example.playCard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByBJndzaYHYFPHU-44pXNgzjt8p-at288',
    appId: '1:147062760195:ios:e9939eb6f6987e1b647f36',
    messagingSenderId: '147062760195',
    projectId: 'playing-e69b2',
    storageBucket: 'playing-e69b2.firebasestorage.app',
    iosBundleId: 'com.example.playCard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHK1p5Zq9Xpaq56E7bEIi8raXTbkOVL_U',
    appId: '1:147062760195:web:8a4f4e6d4b833edc647f36',
    messagingSenderId: '147062760195',
    projectId: 'playing-e69b2',
    authDomain: 'playing-e69b2.firebaseapp.com',
    storageBucket: 'playing-e69b2.firebasestorage.app',
    measurementId: 'G-1QF066DJMK',
  );
}
