import 'package:bhabhi_thulla/constant/export_file.dart';
import 'package:playing_cards/playing_cards.dart';
//new

List profileDataList = [
  {"title": "GAMES PLAYED", "value": "12", "image": AppImages.game, "p": false},
  {"title": "GAMES WON", "value": "12", "image": AppImages.won, "p": false},
  {"title": "WIN RATE", "value": "12", "image": AppImages.winTarget, "p": true},
  {"title": "QUIT RATE", "value": "12", "image": AppImages.exit, "p": true},
  {
    "title": "BHABHI COUNT",
    "value": "12",
    "image": AppImages.bhabhi,
    "p": false,
  },
  {
    "title": "THULLA COUNT",
    "value": "12",
    "image": AppImages.thulla,
    "p": false,
  },
  {
    "title": "WIN STREAK",
    "value": "12",
    "image": AppImages.winStreak,
    "p": false,
  },
  {"title": "BEST WIN", "value": "12", "image": AppImages.bestWin, "p": false},
];

List profileLists = [
  AppImages.p1,
  AppImages.p2,
  AppImages.p3,
  AppImages.p4,
  AppImages.p5,
  AppImages.p6,
  AppImages.p7,
  AppImages.p8,
  AppImages.p9,
  AppImages.p10,
  AppImages.p11,
  AppImages.p12,
  AppImages.p13,
  AppImages.p14,
  AppImages.p15,
  AppImages.p16,
  AppImages.p17,
  AppImages.p18,
  AppImages.p19,
  AppImages.p20,
];

final List<String> profileOptions = [
  AppImages.profile,
  AppImages.avatar,
  AppImages.theme,
  AppImages.emojis,
  AppImages.cards,
];

// past

final List<CardValue> ranks = [
  CardValue.ace,
  CardValue.two,
  CardValue.three,
  CardValue.four,
  CardValue.five,
  CardValue.six,
  CardValue.seven,
  CardValue.eight,
  CardValue.nine,
  CardValue.ten,
  CardValue.jack,
  CardValue.queen,
  CardValue.king,
];
final List<Suit> suits = [Suit.spades, Suit.hearts, Suit.diamonds, Suit.clubs];

/// variables
final List<GameRoom> rooms = [
  GameRoom(prize: 160, entryFee: 120),
  GameRoom(prize: 380, entryFee: 300),
  GameRoom(prize: 760, entryFee: 600),
  GameRoom(prize: 1500, entryFee: 1200),
  GameRoom(prize: 3200, entryFee: 2500),
  GameRoom(prize: 6500, entryFee: 5200),
];

final Map<String, String> flags = {
  "AF": "🇦🇫",
  "AL": "🇦🇱",
  "DZ": "🇩🇿",
  "AD": "🇦🇩",
  "AO": "🇦🇴",
  "AG": "🇦🇬",
  "AR": "🇦🇷",
  "AM": "🇦🇲",
  "AU": "🇦🇺",
  "AT": "🇦🇹",
  "AZ": "🇦🇿",
  "BS": "🇧🇸",
  "BH": "🇧🇭",
  "BD": "🇧🇩",
  "BB": "🇧🇧",
  "BY": "🇧🇾",
  "BE": "🇧🇪",
  "BZ": "🇧🇿",
  "BJ": "🇧🇯",
  "BT": "🇧🇹",
  "BO": "🇧🇴",
  "BA": "🇧🇦",
  "BW": "🇧🇼",
  "BR": "🇧🇷",
  "BN": "🇧🇳",
  "BG": "🇧🇬",
  "BF": "🇧🇫",
  "BI": "🇧🇮",
  "CV": "🇨🇻",
  "KH": "🇰🇭",
  "CM": "🇨🇲",
  "CA": "🇨🇦",
  "CF": "🇨🇫",
  "TD": "🇹🇩",
  "CL": "🇨🇱",
  "CN": "🇨🇳",
  "CO": "🇨🇴",
  "KM": "🇰🇲",
  "CG": "🇨🇬",
  "CD": "🇨🇩",
  "CR": "🇨🇷",
  "CI": "🇨🇮",
  "HR": "🇭🇷",
  "CU": "🇨🇺",
  "CY": "🇨🇾",
  "CZ": "🇨🇿",
  "DK": "🇩🇰",
  "DJ": "🇩🇯",
  "DM": "🇩🇲",
  "DO": "🇩🇴",
  "TL": "🇹🇱",
  "EC": "🇪🇨",
  "EG": "🇪🇬",
  "SV": "🇸🇻",
  "GQ": "🇬🇶",
  "ER": "🇪🇷",
  "EE": "🇪🇪",
  "SZ": "🇸🇿",
  "ET": "🇪🇹",
  "FJ": "🇫🇯",
  "FI": "🇫🇮",
  "FR": "🇫🇷",
  "GA": "🇬🇦",
  "GM": "🇬🇲",
  "GE": "🇬🇪",
  "DE": "🇩🇪",
  "GH": "🇬🇭",
  "GR": "🇬🇷",
  "GD": "🇬🇩",
  "GT": "🇬🇹",
  "GN": "🇬🇳",
  "GW": "🇬🇼",
  "GY": "🇬🇾",
  "HT": "🇭🇹",
  "HN": "🇭🇳",
  "HU": "🇭🇺",
  "IS": "🇮🇸",
  "IN": "🇮🇳",
  "ID": "🇮🇩",
  "IR": "🇮🇷",
  "IQ": "🇮🇶",
  "IE": "🇮🇪",
  "IL": "🇮🇱",
  "IT": "🇮🇹",
  "JM": "🇯🇲",
  "JP": "🇯🇵",
  "JO": "🇯🇴",
  "KZ": "🇰🇿",
  "KE": "🇰🇪",
  "KI": "🇰🇮",
  "KP": "🇰🇵",
  "KR": "🇰🇷",
  "KW": "🇰🇼",
  "KG": "🇰🇬",
  "LA": "🇱🇦",
  "LV": "🇱🇻",
  "LB": "🇱🇧",
  "LS": "🇱🇸",
  "LR": "🇱🇷",
  "LY": "🇱🇾",
  "LI": "🇱🇮",
  "LT": "🇱🇹",
  "LU": "🇱🇺",
  "MG": "🇲🇬",
  "MW": "🇲🇼",
  "MY": "🇲🇾",
  "MV": "🇲🇻",
  "ML": "🇲🇱",
  "MT": "🇲🇹",
  "MH": "🇲🇭",
  "MR": "🇲🇷",
  "MU": "🇲🇺",
  "MX": "🇲🇽",
  "FM": "🇫🇲",
  "MD": "🇲🇩",
  "MC": "🇲🇨",
  "MN": "🇲🇳",
  "ME": "🇲🇪",
  "MA": "🇲🇦",
  "MZ": "🇲🇿",
  "MM": "🇲🇲",
  "NA": "🇳🇦",
  "NR": "🇳🇷",
  "NP": "🇳🇵",
  "NL": "🇳🇱",
  "NZ": "🇳🇿",
  "NI": "🇳🇮",
  "NE": "🇳🇪",
  "NG": "🇳🇬",
  "MK": "🇲🇰",
  "NO": "🇳🇴",
  "OM": "🇴🇲",
  "PK": "🇵🇰",
  "PW": "🇵🇼",
  "PS": "🇵🇸",
  "PA": "🇵🇦",
  "PG": "🇵🇬",
  "PY": "🇵🇾",
  "PE": "🇵🇪",
  "PH": "🇵🇭",
  "PL": "🇵🇱",
  "PT": "🇵🇹",
  "QA": "🇶🇦",
  "RO": "🇷🇴",
  "RU": "🇷🇺",
  "RW": "🇷🇼",
  "KN": "🇰🇳",
  "LC": "🇱🇨",
  "VC": "🇻🇨",
  "WS": "🇼🇸",
  "SM": "🇸🇲",
  "ST": "🇸🇹",
  "SA": "🇸🇦",
  "SN": "🇸🇳",
  "RS": "🇷🇸",
  "SC": "🇸🇨",
  "SL": "🇸🇱",
  "SG": "🇸🇬",
  "SK": "🇸🇰",
  "SI": "🇸🇮",
  "SB": "🇸🇧",
  "SO": "🇸🇴",
  "ZA": "🇿🇦",
  "SS": "🇸🇸",
  "ES": "🇪🇸",
  "LK": "🇱🇰",
  "SD": "🇸🇩",
  "SR": "🇸🇷",
  "SE": "🇸🇪",
  "CH": "🇨🇭",
  "SY": "🇸🇾",
  "TJ": "🇹🇯",
  "TZ": "🇹🇿",
  "TH": "🇹🇭",
  "TG": "🇹🇬",
  "TO": "🇹🇴",
  "TT": "🇹🇹",
  "TN": "🇹🇳",
  "TR": "🇹🇷",
  "TM": "🇹🇲",
  "TV": "🇹🇻",
  "UG": "🇺🇬",
  "UA": "🇺🇦",
  "AE": "🇦🇪",
  "GB": "🇬🇧",
  "US": "🇺🇸",
  "UY": "🇺🇾",
  "UZ": "🇺🇿",
  "VU": "🇻🇺",
  "VA": "🇻🇦",
  "VE": "🇻🇪",
  "VN": "🇻🇳",
  "YE": "🇾🇪",
  "ZM": "🇿🇲",
  "ZW": "🇿🇼",
};
